service: simple-service-express-serverless #Name of your App

provider:
 name: aws
 runtime: nodejs12.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: production
 region: sa-east-1 # AWS region

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY /{proxy+}
     - http: ANY /
